version: 2

sources:
  - name: weather_raw
    database: project-256beac9-89c1-4aed-ab4
    schema: weather_raw
    tables:
      - name: daily_weather
        description: "Raw daily weather data loaded from the Open-Meteo API for 5 cities."
        columns:
          - name: time
            description: "The date of the observation."
          - name: city
            description: "City name."
          - name: temperature_2m_max
            description: "Max daily temperature at 2m, in Celsius."
          - name: temperature_2m_min
            description: "Min daily temperature at 2m, in Celsius."
          - name: temperature_2m_mean
            description: "Mean daily temperature at 2m, in Celsius."
          - name: precipitation_sum
            description: "Total daily precipitation, in mm."
          - name: windspeed_10m_max
            description: "Max daily windspeed at 10m."
          - name: relative_humidity_2m_mean
            description: "Mean daily relative humidity at 2m, in percent."
          - name: uv_index_max
            description: "Max daily UV index."
          - name: surface_pressure_mean
            description: "Mean daily surface pressure."
          - name: latitude
            description: "Latitude of the city."
          - name: longitude
            description: "Longitude of the city."